// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
